### ISSUE TITLE
`no-unused-disable` does not work within Markdown files

### ISSUE THREAD

**Issue by ehmicky** [mysticatea/eslint-plugin-eslint-comments#23]
`README.md`:

````md
<!-- eslint-disable no-inline-comments -->

```js
var aa = true
```
````

`.eslintrc.yml`:

```yml
plugins:
  - eslint-comments
  - markdown
rules:
  no-inline-comments: 2
  eslint-comments/no-unused-disable: 2
```

In the terminal:

```bash
$ eslint README.md
```
The command does not report any errors. However `no-unused-disable` should be reported.

Versions:
  - `eslint`: `5.16.0` (also fails with `6.0.0-alpha.0`)
  - `eslint-plugin-eslint-comments`: `3.1.1`
  - `eslint-plugin-markdown`: `1.0.0`

I am not sure whether the issue comes from `eslint-plugin-eslint-comments` or `eslint-plugin-markdown`, so I decided to report this bug here.
